"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "src/main/resources/assets/frostiful/lang/en_us.json",
    "translation": "src/main/resources/assets/frostiful/lang/%locale_with_underscore%.json",
    "languages_mapping": {
      "locale_with_underscore": {
        "fr": "fr_fr",
        "es-ES": "es_es",
        "de": "de_de",
        "fi": "fi_fi",
        "ja": "ja_jp",
        "pt-PT": "pt_pt",
        "ru": "ru_ru",
        "uk": "uk_ua",
        "zh-CN": "zh_cn",
        "vi": "vi_vn",
        "pt-BR": "pt_br",
        "es-AR": "es_ar",
        "es-MX": "es_mx",
        "en-GB": "en_gb",
        "fr-CA": "fr_ca",
        "en-PT": "en_pt",
      }
    }
  }
]
