# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx8G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
parchment_version=1.21.10
parchment_mappings=2025.10.12@zip
loader_version=0.18.4

# Mod Properties
mod_version=2.2.14+1.21.11
maven_group=com.github.thedeathlycow
archives_base_name=frostiful

# Dependencies

# actually fabric api
fabric_version=0.140.2+1.21.11

mod_menu_version=17.0.0-beta.1
cloth_config_version=21.11.153

# Thermoo
thermoo_version=9.0.0

# Colorful Hearts (10.3.8)
colorful_hearts_version=r2mnc8w2

cardinal_components_version=7.3.0
trinkets_version=3.11.0-1.21.11
