# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true

# Project
version=3.1.0+26.1.x-beta.3
group=com.github.thedeathlycow

# Common
mod_id=frostiful
mod_name=Frostiful
mod_author=TheDeathlyCow
license=LGPL-3.0
description=A Vanilla+ Freezing Temperature Mod. Also try Scorchful!
credits=
java_version=25
minecraft_version=26.1.2

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_loader_version=0.19.2
fabric_version=0.155.2+26.1.2
minecraft_version_predicate=~26.1-

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.2.97
neoforge_loader_version_range=[4,)
minecraft_version_range=[26.1,26.2)

mod_menu_version=18.0.0-beta.1
yacl_version=3.9.4+26.1

# Dependencies
## Common
thermoo_version=10.1.6
yumi_mc_foundation_version=1.1.0+26.1

## Fabric
cca_version=8.0.0
trinkets_version=4.0.0-beta.2+26.1
# 26.1.2.0
colorful_hearts_version=YC1JE0Uv

## Neoforge
ffapi_subversion=3.5.5
unruled_version=qXiGMlFi