# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.219
loader_version_range=[1,)

## Mod Properties
mod_id=frostiful
mod_name=Frostiful
mod_license=LGPL-3.0
mod_version=2.3.1+1.21.1-neoforge
mod_group_id=com.github.thedeathlycow.frostiful
mod_authors=TheDeathlyCow
mod_description=A Vanilla+ Freezing Temperature Mod. Also try Scorchful!

# Dependencies
ffapi_version=0.115.6+2.1.4+1.21.1
cloth_config_version=15.0.140
thermoo_version=4.8.1-neoforge
colorful_hearts_version=us0gze50
accessories_version=1.1.0-beta.53+1.21.1
yumi_mc_version=1.0.0-beta.1+1.21.1
