pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Neoforge'
            url = 'https://maven.neoforged.net/'
        }
        maven {
            name = 'RelativityMC'
            url = 'https://repo.codemc.io/repository/relativitymc/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

// This should match the folder name of the project, or else IDEA may complain (see https://youtrack.jetbrains.com/issue/IDEA-317606)
rootProject.name = 'frostiful'
include('common')
include('fabric')
include('neoforge')