# This is an example neoforge.mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="javafml"

loaderVersion="${loader_version_range}"
license="${mod_license}"

issueTrackerURL="https://www.github.com/TheDeathlyCow/frostiful/issues"

[[mods]]

modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

displayURL="https://frostiful.thedeathlycow.com"

logoFile="assets/frostiful/icon.png"

#credits="" #optional

authors="${mod_authors}"

description='''${mod_description}'''

[modproperties.${mod_id}."yumi:entrypoints"]
"yumi:init" = "com.github.thedeathlycow.frostiful.Frostiful"
"yumi:client_init" = "com.github.thedeathlycow.frostiful.FrostifulClient"

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
config="${mod_id}.mixins.json"

[[mixins]]
config="${mod_id}.client.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="cloth_config"
    type="required"
    versionRange="[${cloth_config_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="fabric_api"
    type="required"
    versionRange="[${ffapi_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="thermoo"
    type="required"
    versionRange="[${thermoo_version},)"
    ordering="AFTER"
    side="BOTH"