plugins {
    id 'multiloader-loader'
    id 'org.relativitymc.neo-loom'
    id 'me.modmuss50.mod-publish-plugin'
}

def commonProject = project(':common')

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    forgeUserdev "net.neoforged:neoforge:${project.neoforge_version}:userdev"
    include("dev.yumi.mc.core:yumi-mc-foundation:${project.yumi_mc_foundation_version}")

    implementation("org.sinytra.forgified-fabric-api:forgified-fabric-api:${project.fabric_version}+${project.ffapi_subversion}")
    implementation("dev.isxander:yet-another-config-lib:${project.yacl_version}-neoforge")

    implementation("maven.modrinth:unruled-api:${project.unruled_version}")
    implementation("com.github.TheDeathlyCow.thermoo:thermoo-neoforge:v${project.thermoo_version}")

    gametestImplementation commonProject.sourceSets.gametest.output

    neoForgeAccessTransformers("org.sinytra.forgified-fabric-api:forgified-fabric-api:${project.fabric_version}+${project.ffapi_subversion}")
    neoForgeInterfaceInjections("org.sinytra.forgified-fabric-api:forgified-fabric-api:${project.fabric_version}+${project.ffapi_subversion}")
}

loom {
    def ct = commonProject.file("src/main/resources/${mod_id}.classtweaker")
    if (ct.exists()) {
        accessWidenerPath.set(ct)
        convertAw2At(tasks.named("jar", Jar), ["${mod_id}.classtweaker"])
    }

    interfaceInjection {
        enableDependencyInterfaceInjection = true
    }

    runs {
        client {
            client()
            setDisplayName("Neoforge Client")
            setGenerateRunConfig(true)
            setRunDirectory(project.file("runs/client"))
        }

        server {
            server()
            setDisplayName("Neoforge Server")
            setGenerateRunConfig(true)
            setRunDirectory(project.file("runs/server"))
        }

        clientManualTest {
            client()
            setDisplayName("Neoforge Manual Test Client")
            setGenerateRunConfig(true)
            setRunDirectory(project.file("runs/clientManualTest"))
            setSourceSet("gametest")
            setSystemProperties(["neoforge.enabledGameTestNamespaces": "${project.mod_id},${project.mod_id}_test"])
        }

        serverManualTest {
            server()
            setDisplayName("Neoforge Manual Test Server")
            setGenerateRunConfig(true)
            setRunDirectory(project.file("runs/serverManualTest"))
            setSourceSet("gametest")
            setSystemProperties(["neoforge.enabledGameTestNamespaces": "${project.mod_id},${project.mod_id}_test"])
        }

        gameTest {
            environment("gameTestServer")
            setDisplayName("Neoforge Game test")
            setGenerateRunConfig(true)
            setRunDirectory(project.file("build/gametest"))
            setSourceSet("gametest")
            setSystemProperties(["neoforge.enabledGameTestNamespaces": "${project.mod_id},${project.mod_id}_test"])
            setJvmArguments([
                    "-Dfabric-api.gametest",
                    "-Dfabric-api.gametest.report-file=${project.layout.buildDirectory.file("junit.xml").get().getAsFile()}"
            ])
        }
    }

    mods {
        mod_id {
            sourceSet("main")
        }

        "${mod_id}_test" {
            sourceSet("gametest")
        }
    }
}

tasks.named('build') {
    dependsOn('runGameTest')
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, 'neoforge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, 'neoforge')
            }
        }
    }
}

publishMods {
    type = STABLE
    def changelogFile = rootProject.file("./changelogs/${project.version}.md")

    if (changelogFile.exists()) {
        changelog = changelogFile.text
    }

    file = jar.archiveFile
    additionalFiles.from(sourcesJar.archiveFile)
    displayName = "Frostiful Neoforge ${version}"

    modLoaders.add("neoforge")

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")
        projectId = "715248"
        minecraftVersions.addAll("26.1", "26.1.1", "26.1.2")

        javaVersions.add(JavaVersion.VERSION_25)

        clientRequired = true
        serverRequired = true

        requires("forgified-fabric-api", "thermoo", "yacl")

        optional("thermoo-patches", "scorchful", "modmenu")
    }

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = "Ae6qoBj3"
        minecraftVersions.addAll("26.1", "26.1.1", "26.1.2")

        requires("forgified-fabric-api", "thermoo", "yacl")

        optional("thermoo-patches", "scorchful", "modmenu", "trinkets-updated")
    }
}